spring.application.name=ProyectoMongoDB-WebMVC

server.port=8090

spring.data.mongodb.uri=mongodb+srv://hpededgar_db_user:qTPAY9pWfUhoQhiO@programacionweb.akphszn.mongodb.net/Escuela?appName=ProgramacionWeb
